import{initializeApp}from"https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";import{getDatabase,ref,get,update,remove}from"https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyCucXDNlA86tU9ACdPm-oZGsAP_keBZ_uo",authDomain:"aps-robotics-championship.firebaseapp.com",databaseURL:"https://aps-robotics-championship-default-rtdb.firebaseio.com",projectId:"aps-robotics-championship",storageBucket:"aps-robotics-championship.firebasestorage.app",messagingSenderId:"1063542904891",appId:"1:1063542904891:web:82ff9bb3fba0b87384a41e"};const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
let registrations={},filtered={},currentKey=null;const $=id=>document.getElementById(id),loginScreen=$("loginScreen"),adminApp=$("adminApp");
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";$("loginBtn").disabled=true;try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(x){$("loginError").textContent=x.code==="auth/invalid-credential"?"Invalid email or password.":"Login failed. Check Firebase Authentication.";console.error(x)}finally{$("loginBtn").disabled=false}});
onAuthStateChanged(auth,async user=>{if(user){loginScreen.classList.add("hidden");adminApp.classList.remove("hidden");$("adminEmail").textContent=user.email||"Authenticated Admin";await loadRegistrations()}else{loginScreen.classList.remove("hidden");adminApp.classList.add("hidden")}});
$("logoutBtn").addEventListener("click",()=>signOut(auth));
$("sidebarToggle").addEventListener("click",()=>{$("sidebar").classList.toggle("open")});
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
document.querySelectorAll("[data-page-target]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.pageTarget)));
function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));$(p+"Page")?.classList.add("active-page");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("pageTitle").textContent=p[0].toUpperCase()+p.slice(1);$("sidebar").classList.remove("open");if(p==="registrations")renderTable();if(p==="events")updateEvents()}
async function loadRegistrations(){setConnection("Loading database…");try{const snap=await get(ref(db,"registrations"));registrations=snap.exists()&&typeof snap.val()==="object"?snap.val():{};filtered={...registrations};setConnection("Firebase connected");populateFilters();updateDashboard();renderRecent();renderTable();updateEvents()}catch(e){console.error("Firebase load error:",e);setConnection(e.code==="PERMISSION_DENIED"?"Database permission denied":"Database connection error");registrations={};filtered={};renderTable();toast(e.code==="PERMISSION_DENIED"?"Firebase denied access. Check Realtime Database Rules.":"Unable to load registrations.")}}
function setConnection(t){$("connectionText").textContent=t}
function norm(v){if(v==null)return"";if(Array.isArray(v))return v.join(", ");if(typeof v==="object")return Object.values(v).join(", ");return String(v)}
function events(d){let v=d?.Events??d?.events??d?.Event??d?.event;if(!v)return[];if(Array.isArray(v))return v.map(norm).filter(Boolean);if(typeof v==="object")return Object.values(v).map(norm).filter(Boolean);return String(v).split(/\s*(?:,|\||;)\s*/).map(x=>x.trim()).filter(Boolean)}
function email(d){return norm(d?.EmailAddress||d?.Email||d?.email).trim()}
function teamSize(d){if(Number(d?.TeamSize)>0)return Number(d.TeamSize);let n=1;for(let i=2;i<=5;i++)if(norm(d?.[`Member${i}Name`]).trim())n++;return n}
function dateValue(d){const t=new Date(d?.registrationDate||0).getTime();return Number.isFinite(t)?t:0}
function dateText(v){if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function esc(v){return norm(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function updateDashboard(){const list=Object.values(registrations),c=countEvents();$("totalRegistrations").textContent=list.length;$("totalTeams").textContent=list.length;$("raceCount").textContent=c.race;$("warCount").textContent=c.war;$("tugCount").textContent=c.tug;$("soccerCount").textContent=c.soccer}
function countEvents(){const c={race:0,war:0,tug:0,soccer:0};Object.values(registrations).forEach(d=>events(d).forEach(e=>{const x=e.toLowerCase().trim();if(x==="robo race")c.race++;if(x==="robo war")c.war++;if(x==="robo tug of war")c.tug++;if(x==="robo soccer")c.soccer++}));return c}
function updateEvents(){const c=countEvents();$("eventRaceCount").textContent=c.race;$("eventWarCount").textContent=c.war;$("eventTugCount").textContent=c.tug;$("eventSoccerCount").textContent=c.soccer}
function renderRecent(){const a=Object.entries(registrations).sort(([,x],[,y])=>dateValue(y)-dateValue(x)).slice(0,6);$("recentRegistrations").innerHTML=a.length?a.map(([k,d])=>`<div class="detail-row"><b>${esc(d.StudentName||"-")}</b> • ${esc(d.TeamName||"-")} <button class="action" data-view="${esc(k)}">View</button></div>`).join(""):"No registrations yet.";document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>openDetails(b.dataset.view)))}
function populateFilters(){const cs=new Set(),ss=new Set();Object.values(registrations).forEach(d=>{if(norm(d.Class))cs.add(norm(d.Class));if(norm(d.Section))ss.add(norm(d.Section))});$("classFilter").innerHTML='<option value="all">All Classes</option>'+[...cs].sort().map(x=>`<option>${esc(x)}</option>`).join("");$("sectionFilter").innerHTML='<option value="all">All Sections</option>'+[...ss].sort().map(x=>`<option>${esc(x)}</option>`).join("")}
["searchInput","eventFilter","classFilter","sectionFilter"].forEach(id=>$(id).addEventListener(id==="searchInput"?"input":"change",applyFilters));
$("clearFilters").addEventListener("click",()=>{$("searchInput").value="";$("eventFilter").value="all";$("classFilter").value="all";$("sectionFilter").value="all";applyFilters()});
function applyFilters(){const q=$("searchInput").value.toLowerCase().trim(),ef=$("eventFilter").value,cf=$("classFilter").value,sf=$("sectionFilter").value;filtered={};Object.entries(registrations).forEach(([k,d])=>{const ev=events(d),hay=[d.registrationId,d.StudentName,d.TeamName,d.Class,d.Section,d.MobileNumber,email(d),...ev].map(norm).join(" ").toLowerCase();if((!q||hay.includes(q))&&(ef==="all"||ev.some(x=>x.toLowerCase()===ef.toLowerCase()))&&(cf==="all"||norm(d.Class)===cf)&&(sf==="all"||norm(d.Section)===sf))filtered[k]=d});renderTable()}
function renderTable(){const rows=Object.entries(filtered).sort(([,a],[,b])=>dateValue(b)-dateValue(a));$("resultCount").textContent=`${rows.length} registration${rows.length===1?"":"s"}`;$("registrationTableBody").innerHTML=rows.map(([k,d])=>`<tr><td>${esc(d.registrationId||k)}</td><td>${esc(d.StudentName||"-")}</td><td>${esc(d.TeamName||"-")}</td><td>${esc(d.Class||"-")}</td><td>${esc(d.Section||"-")}</td><td>${esc(d.MobileNumber||"-")}</td><td>${events(d).map(e=>`<span class="event-tag">${esc(e)}</span>`).join("")||"-"}</td><td>${teamSize(d)}</td><td>${esc(dateText(d.registrationDate))}</td><td><button class="action" data-view="${esc(k)}">View</button><button class="action" data-edit="${esc(k)}">Edit</button><button class="action danger" data-delete="${esc(k)}">Delete</button></td></tr>`).join("");$("tableEmpty").classList.toggle("hidden",rows.length>0);document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>openDetails(b.dataset.view));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteRegistration(b.dataset.delete))}
function openDetails(k){const d=registrations[k];if(!d)return;currentKey=k;$("detailsContent").innerHTML=Object.entries({ID:d.registrationId||k,"Team Leader":d.StudentName,"Team Name":d.TeamName,Class:d.Class,Section:d.Section,Mobile:d.MobileNumber,Email:email(d),Events:events(d).join(", "),Members:teamSize(d),"Date":dateText(d.registrationDate),Remarks:d.Remarks||"None"}).map(([a,b])=>`<div class="detail-row"><b>${esc(a)}</b><br>${esc(b)}</div>`).join("");$("detailsModal").classList.remove("hidden")}
function openEdit(k){const d=registrations[k];if(!d)return;$("editKey").value=k;$("editStudentName").value=norm(d.StudentName);$("editTeamName").value=norm(d.TeamName);$("editClass").value=norm(d.Class);$("editSection").value=norm(d.Section);$("editMobile").value=norm(d.MobileNumber);$("editEmail").value=email(d);$("editRemarks").value=norm(d.Remarks);$("editModal").classList.remove("hidden")}
$("editForm").addEventListener("submit",async e=>{e.preventDefault();const k=$("editKey").value;try{const u={StudentName:$("editStudentName").value.trim(),TeamName:$("editTeamName").value.trim(),Class:$("editClass").value.trim(),Section:$("editSection").value.trim(),MobileNumber:$("editMobile").value.trim(),EmailAddress:$("editEmail").value.trim(),Remarks:$("editRemarks").value.trim()};await update(ref(db,"registrations/"+k),u);registrations[k]={...registrations[k],...u};filtered[k]=registrations[k];$("editModal").classList.add("hidden");updateDashboard();renderRecent();renderTable();updateEvents();toast("Registration updated.")}catch(e){console.error(e);toast("Update failed. Check database rules.")}});
async function deleteRegistration(k){const d=registrations[k];if(!d||!confirm(`Delete registration for ${d.StudentName||"this team"}?`))return;try{await remove(ref(db,"registrations/"+k));delete registrations[k];delete filtered[k];$("detailsModal").classList.add("hidden");updateDashboard();renderRecent();renderTable();updateEvents();toast("Registration deleted.")}catch(e){console.error(e);toast("Delete failed. Check database rules.")}}
$("dashboardRefresh").onclick=loadRegistrations;$("refreshRegistrations").onclick=loadRegistrations;
$("exportCsv").onclick=()=>exportCSV(filtered);
function exportCSV(obj){const rows=[["Registration ID","Team Leader","Team Name","Class","Section","Mobile","Email","Events","Team Size","Member 2","Member 3","Member 4","Member 5","Remarks","Registration Date"],...Object.entries(obj).map(([k,d])=>[d.registrationId||k,d.StudentName,d.TeamName,d.Class,d.Section,d.MobileNumber,email(d),events(d).join(" | "),teamSize(d),d.Member2Name,d.Member3Name,d.Member4Name,d.Member5Name,d.Remarks,d.registrationDate])];const csv=rows.map(r=>r.map(v=>`"${norm(v).replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download="APS_Robotics_Registrations_2026.csv";a.click();toast("CSV exported.")}
document.querySelectorAll("[data-close-modal]").forEach(b=>b.onclick=()=>document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden")));$("modalDeleteBtn").onclick=()=>currentKey&&deleteRegistration(currentKey);document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"))});
let toastTimer;function toast(m){const x=$("toast");x.textContent=m;x.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove("show"),3000)}
