const rules=[
["GENERAL RULES",["Every team must complete registration before the announced deadline.","Participants must follow instructions of organizers, judges and volunteers.","Teams must bring their robot in competition-ready condition.","Any unsafe or disruptive behavior may result in disqualification."]],
["TEAM RULES",["A team must use the members declared during registration.","Only registered team members may operate or represent the team during a match.","Teams should report to the venue before their scheduled reporting time.","Team identity and registration details may be verified at check-in."]],
["ROBO RACE",["Robot must remain within the designated race area.","The robot should be controlled by the registered team.","Intentional interference with another robot is not permitted.","The fastest valid completion determines the result where applicable."]],
["ROBO WAR",["Combat must take place only inside the designated arena.","Robots must comply with the technical and safety limits announced by organizers.","Teams must stop operation immediately when instructed by officials.","Unsafe modifications may be rejected before or during inspection."]],
["ROBO TUG OF WAR",["Both robots must begin from the designated starting positions.","The match is decided according to the marked boundary and organizer scoring system.","Deliberate interference outside the match area is prohibited.","Officials' decision on the result is final for the match."]],
["ROBO SOCCER",["Robots must operate within the marked playing field.","Teams must follow the match time and scoring procedure announced by organizers.","Physical interference by participants during play is not allowed.","The team with the higher valid score wins the match."]],
["SAFETY & FAIR PLAY",["Keep batteries, wiring and moving parts properly secured.","Do not operate robots outside permitted areas.","Respect other teams, equipment and venue property.","Report technical or safety concerns to the technical team immediately."]]
];
document.getElementById("rulesList").innerHTML=rules.map((r,i)=>`<article class="rule-card"><span class="num">RULE ${String(i+1).padStart(2,"0")}</span><h2>${r[0]}</h2><ul>${r[1].map(x=>`<li>${x}</li>`).join("")}</ul></article>`).join("");